"""Added account table

Revision ID: 4096347373f7
Revises: 
Create Date: 2024-01-23 22:41:51.918814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4096347373f7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.add_column('students',sa.Column('grade',sa.Enum("grade_1","grade_2","grade_3","grade_4","grade_5","grade_6","grade_7","grade_8","grade_9","grade_10","grade_11","grade_12",name="grade"),nullable=True))

    op.create_index(op.f('ix_students_address'), 'students', ['address'], unique=False)
    op.create_index(op.f('ix_students_email'), 'students', ['email'], unique=True)
    op.create_index(op.f('ix_students_first_name'), 'students', ['first_name'], unique=False)
    op.create_index(op.f('ix_students_last_name'), 'students', ['last_name'], unique=False)
    op.create_index(op.f('ix_students_phone_number'), 'students', ['phone_number'], unique=False)
    op.create_index(op.f('ix_students_student_id'), 'students', ['student_id'], unique=False)
    op.create_table('subject',
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('subject_name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('subject_id')
    )
    op.create_index(op.f('ix_subject_subject_id'), 'subject', ['subject_id'], unique=True)
    op.create_index(op.f('ix_subject_subject_name'), 'subject', ['subject_name'], unique=True)
    op.create_table('teachers',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('teacher_id')
    )
    op.create_index(op.f('ix_teachers_address'), 'teachers', ['address'], unique=False)
    op.create_index(op.f('ix_teachers_email'), 'teachers', ['email'], unique=True)
    op.create_index(op.f('ix_teachers_first_name'), 'teachers', ['first_name'], unique=False)
    op.create_index(op.f('ix_teachers_last_name'), 'teachers', ['last_name'], unique=False)
    op.create_index(op.f('ix_teachers_phone_number'), 'teachers', ['phone_number'], unique=False)
    op.create_index(op.f('ix_teachers_teacher_id'), 'teachers', ['teacher_id'], unique=False)
    op.create_table('class',
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], ),
    sa.PrimaryKeyConstraint('class_id')
    )
    op.create_index(op.f('ix_class_class_id'), 'class', ['class_id'], unique=False)
    op.create_index(op.f('ix_class_student_id'), 'class', ['student_id'], unique=False)
    op.create_index(op.f('ix_class_teacher_id'), 'class', ['teacher_id'], unique=False)
    op.create_table('attendance',
    sa.Column('attendance_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class.class_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('attendance_id')
    )
    op.create_index(op.f('ix_attendance_attendance_id'), 'attendance', ['attendance_id'], unique=False)
    op.create_index(op.f('ix_attendance_class_id'), 'attendance', ['class_id'], unique=False)
    op.create_index(op.f('ix_attendance_student_id'), 'attendance', ['student_id'], unique=False)
    op.create_table('enrollment',
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class.class_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('enrollment_id')
    )
    op.create_index(op.f('ix_enrollment_class_id'), 'enrollment', ['class_id'], unique=False)
    op.create_index(op.f('ix_enrollment_enrollment_id'), 'enrollment', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_enrollment_student_id'), 'enrollment', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enrollment_student_id'), table_name='enrollment')
    op.drop_index(op.f('ix_enrollment_enrollment_id'), table_name='enrollment')
    op.drop_index(op.f('ix_enrollment_class_id'), table_name='enrollment')
    op.drop_table('enrollment')
    op.drop_index(op.f('ix_attendance_student_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_class_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_attendance_id'), table_name='attendance')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_class_teacher_id'), table_name='class')
    op.drop_index(op.f('ix_class_student_id'), table_name='class')
    op.drop_index(op.f('ix_class_class_id'), table_name='class')
    op.drop_table('class')
    op.drop_index(op.f('ix_teachers_teacher_id'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_phone_number'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_last_name'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_first_name'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_email'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_address'), table_name='teachers')
    op.drop_table('teachers')
    op.drop_index(op.f('ix_subject_subject_name'), table_name='subject')
    op.drop_index(op.f('ix_subject_subject_id'), table_name='subject')
    op.drop_table('subject')
    op.drop_index(op.f('ix_students_student_id'), table_name='students')
    op.drop_index(op.f('ix_students_phone_number'), table_name='students')
    op.drop_index(op.f('ix_students_last_name'), table_name='students')
    op.drop_index(op.f('ix_students_first_name'), table_name='students')
    op.drop_index(op.f('ix_students_email'), table_name='students')
    op.drop_index(op.f('ix_students_address'), table_name='students')
    op.drop_table('students')
    # ### end Alembic commands ###
